### ISSUE TITLE
Laboratory revamp wishlist

### ISSUE THREAD

**Issue by vcarl** [stellar/laboratory#417]
There are a number of smaller features that I think we'd like to implement, but not until we tackle a broader overhaul of the Laboratory UX. I'm going to close those issues out and list them here to keep the backlog tidy.

* [ ] Display fee stats in transaction builder (#391).
* [ ] Base fee should be optional (#382).
* [ ] Import XDR to transaction builder (#375).
* [ ] Transaction builder validation doesn't match server rules (#181).
* [ ] Search XDR types in XDR viewer (#327, #326).
* [ ] Tighten up form UX. There are numerous usability problems with forms. Some generate results offscreen as you type, some don't submit when you pretty `enter`, etc.
* [ ] Provide a better "onboarding" experience for new Stellar users (#149).
* [ ] Sign/verify message tool (#174).
* [ ] Improve UX for streaming API responses (#99, #101, #103, #104).
* [ ] Better communicate that secret keys should be protected (#75)

**Comment by vcarl** [comment]
5 years later!!! I had a working prototype for a Lab v2 in 2019 that resolved these issues, wow
