### ISSUE TITLE
Lab refactor: Tier 1 work

### ISSUE THREAD

**Issue by shanzzam** [stellar/laboratory#554]
- [x] #547
- [x] #550
- [x] #552 
- [x] #556 
- [x] Update outdated dependencies (https://github.com/stellar/laboratory/pull/553)
- [x] Update Webpack to properly interpolate TS files (https://github.com/stellar/laboratory/pull/553)
- [x] https://github.com/stellar/laboratory/issues/571
- [x] #573
