### ISSUE TITLE
Page - Explore Endpoints

### ISSUE THREAD

**Issue by quietbits** [stellar/laboratory#751]
```[tasklist]
### Tasks
- [ ] https://github.com/stellar/laboratory/issues/765
- [ ] https://github.com/stellar/laboratory/issues/774
- [ ] https://github.com/stellar/laboratory/issues/766
- [ ] https://github.com/stellar/laboratory/issues/767
- [ ] https://github.com/stellar/laboratory/issues/768
- [ ] https://github.com/stellar/laboratory/issues/790
```
