### ISSUE TITLE
Page - Build Transaction

### ISSUE THREAD

**Issue by quietbits** [stellar/laboratory#752]
```[tasklist]
### Tasks
- [ ] https://github.com/stellar/laboratory/issues/821
- [ ] https://github.com/stellar/laboratory/issues/822
- [ ] https://github.com/stellar/laboratory/issues/823
- [ ] https://github.com/stellar/laboratory/issues/837
```
